/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Retangulo r1 = new Retangulo(10, 12);
        Retangulo r2 = new Retangulo(11);
        Retangulo r3 = new Retangulo();
        r3.setAltura(2);
        r3.setBase(3);
        System.out.println(r2.toString());
        System.out.println(r1.toString());
        System.out.println(r3.calculaArea());
        System.out.println(r3.calculaPerimetro());
        Cilindro c1 = new Cilindro(r1, 12);
        Cilindro c2 = new Cilindro(13);
        Cilindro c3 = new Cilindro();
        c3.setBaseCilindro(r1);
        c3.setAlturaCilindro(15);
        System.out.println(c1.toString());
        System.out.println(c2.toString());
        System.out.println(c3.calcularVolume());
        System.out.println(c3.toString());
    }
}
